### PR TITLE
Web View Reader Mode

### PR DESCRIPTION
**Pull request by seletz**
Add new option  to allow the web view to enter reader
mode on href actions.

Implements #44

### CODE REVIEW

**Comment by gliechtenstein** [comment]
Hmm i'm not sure about adding more attributes to href at root level. 

Currently `href` has only `view`, `url`, `options`, and `transition` so it's easy enough to remember. (Although we're discussing about adding just one more attribute called `data` [here](https://github.com/Jasonette/JASONETTE-iOS/issues/43) but that's another story)

Maybe we can instead add it under `options` instead of at the root level?

For example:

``` json
{
  "href": {
    "url": "https://www.google.com",
    "options": {
      "reader_mode": "true"
    }
```

**Comment by thedumbtechguy** [comment]
I agree

**Comment by ghost** [comment]
was there any follow up to this? I'd love to be able to use "web" view in reader mode if it's possible. The commit doesn't seem to have ever been merged?

**Comment by clsource** [comment]
added in this pull request https://github.com/jasonelle/jasonette-ios/pull/1

as options

```json
{
	"options": {
		"reader": true
	}
}
```

**Pull request closed without merging**
