### PR TITLE
Fixed minor typo in doc

### PR DESCRIPTION
**Pull request by pborreli**

### CODE REVIEW

**Comment by gliechtenstein** [comment]
Thank you! Feel free to make corrections anytime you see something wrong! I've worked on this entire documentation alone and by the end I got too much fatigued that I think I may have overlooked a lot of parts :)

**Comment by pborreli** [comment]
will do, thanks for sharing this great project, keep the good work

**Comment by pborreli** [comment]
see Jasonette/documentation#5

**Comment by moehawkins** [comment]
So do you guys ever grow a set of balls and face these people in real life or do you always hide behind your computer screens like scared little bitches? Hey guys look I fixed a typo. Thanks man I was working real hard pushing these little button on this keyboard. Yep at one point I even got a hang nail but I just pushed through it and never stopped. DOUCHEBAGS!!!!

**Pull request merged**
