### PR TITLE
Issue 82,loading indicator

### PR DESCRIPTION
**Pull request by wajahatch888**
Loading indicator added on following

1. **Initail url load**
     loading property is added in settings.plist.
2. **Href load url**
    `"href": {
    "url": "https://jasonbase.com/things/dhe.json",
    "loading": "true"
  }`
3. **Network Request**
   `"reload": {
          "type": "$network.request",
          "options": {
            "url": "https://hardwax.com/this-week/",
            "dataType": "html",
            "loading", "true",
          },`

### CODE REVIEW

**Comment by gliechtenstein** [comment]
Awesome! Could you run `pod install` and commit that as well, so that it can be directly integrated without a separate `pod install` from user side? Thanks!

**Comment by gliechtenstein** [comment]
BTW trying it out now and looks great! 

Just one quick question: Is it possible to add a "fade out" animation? Just thought it would be nice if the loading faded away instead of suddenly disappearing. 

But if it's too much hassle or hacky don't worry about it, it's great as is :)

**Comment by wajahatch888** [comment]
@gliechtenstein , i will find some time to add "fade out" animation. One more thing, In future i will also add a feature to customise loader too.

**Comment by wajahatch888** [comment]
@gliechtenstein , `MBProgressHud` added in git.

**Comment by wajahatch888** [comment]
Fade In / Fade out animation added.

**Comment by gliechtenstein** [comment]
Hmm for some reason not all files from `pod install` seem to be included in the final build.  It was missing some files which resulted in a build failure.

So I tried snapshotting before `pod install` and after. Below are the files that seem to be missing from the commit. Could you take a look? (Could it be a difference in CocoaPods binary version?) Maybe I'm missing something.. Thanks!

screen shot 2016-12-24 at 5 10 28 pm

**Comment by gliechtenstein** [comment]
@wajahatch888 I think `loader` can be more misleading than `loading` because people may interpret this as some module that loads the new view.

Let's just go with `loading` for now, we can always add another option to describe this later if we wanted to.

**Comment by gliechtenstein** [comment]
Thanks @wajahatch888 ! Great Christmas present :)

**Comment by lukeramsden** [comment]
Nice work @wajahatch888 +1

**Pull request merged**
