### PR TITLE
Azure Mobile Action

### PR DESCRIPTION
**Pull request by seletz**
Added basic implementation of an AzureMobile table query action.

### CODE REVIEW

**Comment by seletz** [comment]
This is how that one would be used:

https://jasonbase.com/things/e41

**Comment by gliechtenstein** [comment]
Wow I first thought this was just push related but upon reading further, is this the full Azure stack? Maybe i misunderstand. More specifically, i'm looking at the `query` method.

**Comment by seletz** [comment]
Yes it has grown.

The query thing basically integrates with the M$ way of doing mobile apps.  It's quite capable.  Basically with a few clicks -- literally -- you get a fully customisable backend based on NodeJS with complete swagger API, database backend.  https://azure.microsoft.com/de-de/services/app-service/mobile/

The query action is used to query a table on tose back ends.

**Comment by gliechtenstein** [comment]
@seletz Did you get this to work as podspec? Was trying to look through the commits and there's too much code (probably due to the Azure library) I couldn't figure out what was going on.

I've started thinking about different approaches to package management so any type of input would be helpful.

**Comment by seletz** [comment]
@gliechtenstein no not really.  To deliver this as POD we need to create a defined interface between the core and actions, or at least I believe so.  Wrt too much code -- it's really just two files, the JasonAzureAction.{h,m}.  The other big chunk is a dependency.  I checked that one in because the app/Pods is version controlled ...

**Comment by seletz** [comment]
@gliechtenstein this is the code needed to get APNS working with Jasonette: https://github.com/Jasonette/JASONETTE-iOS/pull/24/commits/59d14b1f6209ae0e30d5b00b9dcf74bf31de1abe

It's a action to be called with the device token.  This registers the device with Azure Mobile.  After this call, APNS messages from Azure Mobile back-end are sent to the device.

**Comment by seletz** [comment]
@gliechtenstein This code https://github.com/Jasonette/JASONETTE-iOS/pull/24/commits/961a177c467ae6679cb89fe9fa613ab760a9fecb is actually a action for querying databases hosted on Azure Mobile.  There's a setting for the back-end URL  and some bootstrapping code to register with Azure Mobile.  Then there are three actions Query, Insert, Delete.  It's a very crude CRUD interface to Azure Mobile backed databases.

**Comment by seletz** [comment]
@gliechtenstein do you want me to split those in two separate PRs?

**Comment by seletz** [comment]
I'll close this one in favour of the new plug-in approcah discussed in #34 and #26

**Pull request closed without merging**
