### PR TITLE
Add Camera or Photo Library action

### PR DESCRIPTION
**Pull request by hoffmabc**
This adds a new $media action called $media.cameraLibrary that presents an UIAlertView to choose between using the camera and the photo library in one view.

image

### CODE REVIEW

**Comment by drwasho** [comment]
w00t

**Comment by gliechtenstein** [comment]
Thanks for the PR @hoffmabc ! One question, couldn't we achieve the same effect purely by composing existing actions? For example:

```json
{
  "type": "$util.picker",
  "options": {
    "items": [
      {
        "text": "Camera",
        "action": {
          "type": "$media.camera"
        }
      },
      {
        "text": "Choose from Library",
        "action": {
          "type": "$media.picker"
        }
      }
    ]
  }
}
```

**Comment by hoffmabc** [comment]
I didn't think about that, but I suppose it could be. Is there still a reason to include this option? If not, it would probably be useful to call out this capability if it's not already in the documentation as it's very useful.

**Comment by drwasho** [comment]
The component that Brian is proposing is a more standard way of selecting to either take a picture or choose an image. The current $util.picker looks a bit odd for this use-case.

**Comment by gliechtenstein** [comment]
> The component that Brian is proposing is a more standard way of selecting to either take a picture or choose an image. The current $util.picker looks a bit odd for this use-case.

Maybe we can solve this problem by switching the `$util.picker` itself to use `UIAlertController`?

It's always good to use the native Cocoa UI elements instead of a 3rd party library anyway (the current `$util.picker` uses a 3rd party library, which is why it looks different).

Also I don't think it's a good idea to create a separate action for something that can be recreated by composing other existing actions. 

Here's what the new `$util.picker` would look like as `UIAlertController`:

img_1486

I guess the main difference would be that by default all texts are center aligned (Apple doesn't expose a public API to align them left). What do you think?

**Comment by gliechtenstein** [comment]
Try this branch https://github.com/Jasonette/JASONETTE-iOS/tree/util_alert_update for the `UIAlertController` based `$util.picker`. I tested it and it's working great for me (and I feel cleaner about getting rid of another 3rd party library dependency) so plan on merging this into `develop` soon. 

This new one will have an additional parameter `title` which will display at the header. Here's what it looks like:

img_1487

Let me know if you think I'm missing something. Otherwise I'll merge soon

**Comment by drwasho** [comment]
ACK (pretentious Bitcoin lingo for +1)

Is there a max number of items that can fit in there, or is it scrollable? Looks like it is scrollable, which is great.

@hoffmabc

**Comment by gliechtenstein** [comment]
Yup it's scrollable. gonna merge this in soon.

**Comment by hoffmabc** [comment]
Yes! Thanks!

**Comment by gliechtenstein** [comment]
Merged the `$util.picker` update at https://github.com/Jasonette/JASONETTE-iOS/pull/225

You can try it with the following code: https://jasonbase.com/things/wLYD

```
{
  "$jason": {
    "head": {
      "actions": {
        "$load": {
          "trigger": "pick"
        },
        "$foreground": {
          "trigger": "pick"
        },
        "pick": {
          "type": "$util.picker",
          "options": {
            "title": "Choose Image",
            "items": [
              {
                "text": "Camera",
                "action": {
                  "type": "$media.camera"
                }
              },
              {
                "text": "Choose from Library",
                "action": {
                  "type": "$media.picker"
                }
              }
            ]
          }
        }
      }
    }
  }
}
```

**Pull request closed without merging**
