### PR TITLE
Implement Switch Component

### PR DESCRIPTION
**Pull request by clsource**
See https://github.com/Jasonette/Jasonette/issues/1
Closes issue #275

Please review.
Thanks.

### CODE REVIEW

**Comment by gliechtenstein** [comment]
Thanks for the PR! Does WIP mean i should wait taking a look? Or is it ready to go?

**Comment by clsource** [comment]
@gliechtenstein I think the code should work, but haven't tested properly with a json.
Please look at the code if there's something odd or anything that could be improved.

Then I'll make the changes and properly test the component
so it can be merged 👍 

Thanks.

**Comment by clsource** [comment]
I tested, seems to work 👍

**Comment by ghost** [comment]
@gliechtenstein  Would it be possible please to put up an example json for the switch. I looked at the [docs](https://docs.jasonette.com/components/#switch) but that example doesn't reference the variable "light" anywhere. I tried to do just that and the app crashes. I'm sure I'm doing it wrong. Ideally I'd be able to change between slider and switch pretty much interchangeably in terms of syntax. Also it would be really useful if you could release a new jason app so I could put up a jsonbase example to try. 

Thanks!

**Pull request merged**
