### PR TITLE
Add border width and color

### PR DESCRIPTION
**Pull request by WenchaoD**
Add border with and color

### CODE REVIEW

**Comment by gliechtenstein** [comment]
@WenchaoD This is really cool! I just tried it on my phone, and it works great for label, but for some reason I couldn't get it to work with an image, do you know why?

**Comment by WenchaoD** [comment]
Just tried, and it seems working fine on image in my simulator and iPhone.

image

The configuration is 

``` json
        {
          "type": "image",
          "url" : "https://pbs.twimg.com/profile_images/557061751150112768/eMwi4Xz2.jpeg",
          "style" : {
              "width" : "200",
              "corner_radius" : "100",
              "border_width" : "3",
              "border_color" : "#FF0000"
          }
        },
```

**Comment by gliechtenstein** [comment]
Got it to work, great! Thanks! 👍👍👍

**Comment by gliechtenstein** [comment]
https://twitter.com/jasonclient/status/796903855204302849 :)

**Pull request merged**
