### PR TITLE
Feature/plugin module handling

### PR DESCRIPTION
**Pull request by seletz**
This is the core code which is needed for #34 to work.

It adds a '@<<classname with method>>'  action which implements the Jasonette side of the notification based plugin handling.

### CODE REVIEW

**Comment by seletz** [comment]
YAY, cool!

**Comment by gliechtenstein** [comment]
👍 👍 👍 👍 🚀  💯

**Comment by gliechtenstein** [comment]
Interesting.. although it shows up on cocoapods.org website, `JasonetteDemoAction` doesn't show up when you try to search on the console using `pod search Jasonette`, nor is `pod install` able to find `JasonetteDemoAction`. Am I doing something wrong?

**Comment by gliechtenstein** [comment]
Fixed it, had to `rm -rf ~/.cocoapods/repos/master` and run `pod install` again for some reason.

**Comment by steve21124** [comment]
can use this way too
pod 'JasonetteDemoAction', :podspec=> 'https://raw.githubusercontent.com/seletz/JasonetteDemoAction/master/JasonetteDemoAction.podspec'

**Pull request merged**
