### PR TITLE
Mix~in for local file

### LINKED ISSUE #147: Minor Bug: Mix~in for local file
great lambda. love it. :) =>https://blog.jasonette.com/2017/02/27/mixins/

Here is the steps to make lambda partially work for local file 
https://jasonbase.com/things/nz7.json => copy as main.json
https://jasonbase.com/things/3bA.json => copy as item.json

in setting.plist, set url to file://main.json

when lunch, it will give this error:
[NSTaggedPointerString objectForKeyedSubscript:]: unrecognized selector sent to instance 0xa0000006c6c756e4

`
- (void) loadViewByFile: (NSString *)url{
  
    if ([url hasPrefix:@"file://"] && [url hasSuffix:@".json"]) {

        NSString *resourcePath = [[NSBundle mainBundle] resourcePath];
        NSString *webrootPath = [resourcePath stringByAppendingPathComponent:@""];  
        NSString *loc = @"file:/";

        NSString *jsonFile = [url stringByReplacingOccurrencesOfString:loc withString:webrootPath];
        NSLog(@"LOCALFILES jsonFile is %@", jsonFile);

        NSFileManager *fileManager = [NSFileManager defaultManager];

        if ([fileManager fileExistsAtPath:jsonFile]) { 
            NSError *error = nil;
            NSInputStream *inputStream = [[NSInputStream alloc] initWithFileAtPath:jsonFile];
            [inputStream open];
            id jsonResponseObject = [NSJSONSerialization JSONObjectWithStream: inputStream options:kNilOptions error:&error];
            [self include:jsonResponseObject andCompletionHandler:^(id res){
                dispatch_async(dispatch_get_main_queue(), ^{                    
                    VC.original = @{@"$jason": res[@"$jason"]};
                    [self drawViewFromJason: VC.original];                    
                });
            }];            
            [inputStream close];
        } else {
            NSLog(@"JASON FILE NOT FOUND: %@", jsonFile);
            [self call:@{@"type": @"$util.banner", 
                                  @"options": @{
                                       @"title": @"Error",
                                       @"description": [NSString stringWithFormat:@"JASON FILE NOT FOUND: %@", url]
                                   }}];

        }
    }
}
`

### PR DESCRIPTION
**Pull request by steve21124**
Fixes #147 

test using these json
https://jasonbase.com/things/nz7.json => copy as main.json
https://jasonbase.com/things/3bA.json => copy as item.json
in setting.plist, set url to file://main.json

### CODE REVIEW

**Comment by gliechtenstein** [comment]
Awesome, thanks for the pull request! I was taking a look and had a question:

https://github.com/Jasonette/JASONETTE-iOS/pull/148/files#diff-f22c800ecb5b9ecf974c06bdcb66ad7cR94 <= Was there a reason why you used `VC.original = @{@"$jason": res[@"$jason"]};` instead of directly using `VC.original = res;`?

With mixins you can include any key in your JSON objects, so unless I'm missing something I think this may break if you try to mix in a local JSON object that has no `$jason` key or has other keys as well.  Let me know!

**Comment by steve21124** [comment]
Good catch. :). That section of code exactly the same as : https://github.com/Jasonette/JASONETTE-iOS/blob/a0cbde00bebc53f18ca1b0fdaf9a8c6222610d5e/app/Jasonette/Jason.m#L1544
I think since on above "Reload" will always has $jason, so that's why it is there. But in here, there is case where it does not has $jason. Feel free to modify it. Or only the pull request person can modify it?

**Comment by gliechtenstein** [comment]
@steve21124 sorry for the late merge! For some reason I actually thought I had merged it, just to find out a minute ago that I didn't. 

Actually this has come to my attention because someone asked me if this was possible, which i thought it was, just to find out it's not yet merged. Anyway this means your feature already has a user, congrats, and thanks for the PR! :D 

p.s. After a little more digging into code I think we're good to go with using the `$jason` unless there's something I'm missing. So no need to update the code!

**Comment by steve21124** [comment]
np. Either way, I have not have a chance to check it out yet. It is too sunny in BayArea. not enough time to do side project over the weekend.

**Comment by gliechtenstein** [comment]
@steve21124 haha enjoy!

**Pull request merged**
